// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2hIoIdBUE35IGUsmWNYnJ7cQfa6tPdlE',
    appId: '1:28903637497:web:e5f54ace7f2d35bec47d28',
    messagingSenderId: '28903637497',
    projectId: 'udrive-7d8c3',
    authDomain: 'udrive-7d8c3.firebaseapp.com',
    databaseURL: 'https://udrive-7d8c3-default-rtdb.firebaseio.com',
    storageBucket: 'udrive-7d8c3.appspot.com',
    measurementId: 'G-ERHF6S7SCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyComvlpCAz6RiGh4CGyak-bw9H0tf1UQhU',
    appId: '1:28903637497:android:a1d58b474cb39323c47d28',
    messagingSenderId: '28903637497',
    projectId: 'udrive-7d8c3',
    databaseURL: 'https://udrive-7d8c3-default-rtdb.firebaseio.com',
    storageBucket: 'udrive-7d8c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx2p4PAm0J7-vbmXmBUqKkUouOvHJSZDg',
    appId: '1:28903637497:ios:ad9a7175e0e88442c47d28',
    messagingSenderId: '28903637497',
    projectId: 'udrive-7d8c3',
    databaseURL: 'https://udrive-7d8c3-default-rtdb.firebaseio.com',
    storageBucket: 'udrive-7d8c3.appspot.com',
    iosClientId: '28903637497-00a2qho7101vg589hn9jfdn630ag0hgp.apps.googleusercontent.com',
    iosBundleId: 'com.udrive.udrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx2p4PAm0J7-vbmXmBUqKkUouOvHJSZDg',
    appId: '1:28903637497:ios:f1542de836b88241c47d28',
    messagingSenderId: '28903637497',
    projectId: 'udrive-7d8c3',
    databaseURL: 'https://udrive-7d8c3-default-rtdb.firebaseio.com',
    storageBucket: 'udrive-7d8c3.appspot.com',
    iosClientId: '28903637497-167i87pljf028kg2fme8ng4dum4c6c64.apps.googleusercontent.com',
    iosBundleId: 'com.udrive.udrive.RunnerTests',
  );
}
